package model

import (
	"strings"
	"time"
)

// External platform SSO "connect" registry. An ExternalApp is a third-party
// platform that TrustMesh can launch on behalf of a user using a short-lived
// SSO token (trustmesh_jwt). The token is verified by the external platform
// using the shared client_secret generated by TrustMesh at creation time.
const (
	ExternalAppStatusEnabled  = "enabled"
	ExternalAppStatusDisabled = "disabled"

	// ExternalSSOTrustmeshJWT: TrustMesh signs an HS256 JWT with the app's
	// client_secret; the external platform verifies it.
	ExternalSSOTrustmeshJWT = "trustmesh_jwt"

	// ExternalFrameNewTab: launch opens the external platform in a new tab
	// carrying the SSO token as a query parameter.
	ExternalFrameNewTab = "newtab"

	// ExternalFrameIframe: launch renders the external platform inside an
	// iframe embedded in the TrustMesh shell. Requires the external platform
	// to allow framing (no X-Frame-Options: DENY / CSP frame-ancestors).
	ExternalFrameIframe = "iframe"

	// Mount points. An app may declare several, comma-separated.
	ExternalPlacementSidebar    = "sidebar"
	ExternalPlacementProjectTab = "project_tab"

	// Visibility. "private" apps are only visible to (and launchable by)
	// their creator; "public" apps are visible to every signed-in user.
	ExternalVisibilityPrivate = "private"
	ExternalVisibilityPublic  = "public"
)

// HasPlacement reports whether the app declares the given mount point.
// Placement is stored as a comma-separated set (e.g. "sidebar,project_tab")
// so a single registration can surface in several places at once.
func HasPlacement(placement, want string) bool {
	for _, p := range strings.Split(placement, ",") {
		if strings.TrimSpace(p) == want {
			return true
		}
	}
	return false
}

// ExternalApp is the persisted connection record (includes the sensitive
// client_secret, which must never be serialized to API clients directly).
type ExternalApp struct {
	ID           string    `json:"id" bson:"_id"`
	Name         string    `json:"name" bson:"name"`
	BaseURL      string    `json:"base_url" bson:"base_url"`
	ClientID     string    `json:"client_id" bson:"client_id"`
	ClientSecret string    `json:"-" bson:"client_secret"`
	SSOType      string    `json:"sso_type" bson:"sso_type"`
	FrameMode    string    `json:"frame_mode" bson:"frame_mode"`
	Scopes       string    `json:"scopes,omitempty" bson:"scopes,omitempty"`

	// Mount metadata: where the app surfaces inside the TrustMesh shell.
	// Placement is a comma-separated set of mount points (sidebar, project_tab);
	// empty means "not mounted anywhere" (management page only).
	Placement string `json:"placement,omitempty" bson:"placement,omitempty"`
	// IconURL is an optional square icon rendered in the sidebar / tab.
	IconURL string `json:"icon_url,omitempty" bson:"icon_url,omitempty"`
	// SortOrder controls position among mounted apps (ascending).
	SortOrder int `json:"sort_order" bson:"sort_order"`
	// Visibility: private (creator only) or public (everyone).
	Visibility string `json:"visibility" bson:"visibility"`

	Status    string    `json:"status" bson:"status"`
	CreatedBy string    `json:"created_by" bson:"created_by"`
	CreatedAt time.Time `json:"created_at" bson:"created_at"`
	UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`
}

// ExternalAppView is the safe projection returned to API clients (no secret).
type ExternalAppView struct {
	ID         string    `json:"id" bson:"_id"`
	Name       string    `json:"name" bson:"name"`
	BaseURL    string    `json:"base_url" bson:"base_url"`
	ClientID   string    `json:"client_id" bson:"client_id"`
	SSOType    string    `json:"sso_type" bson:"sso_type"`
	FrameMode  string    `json:"frame_mode" bson:"frame_mode"`
	Scopes     string    `json:"scopes,omitempty" bson:"scopes,omitempty"`
	Placement  string    `json:"placement,omitempty" bson:"placement,omitempty"`
	IconURL    string    `json:"icon_url,omitempty" bson:"icon_url,omitempty"`
	SortOrder  int       `json:"sort_order" bson:"sort_order"`
	Visibility string    `json:"visibility" bson:"visibility"`
	Status     string    `json:"status" bson:"status"`
	CreatedBy  string    `json:"created_by" bson:"created_by"`
	CreatedAt  time.Time `json:"created_at" bson:"created_at"`
	UpdatedAt  time.Time `json:"updated_at" bson:"updated_at"`
}

// ToView returns the safe projection (omits client_secret).
func (a *ExternalApp) ToView() *ExternalAppView {
	if a == nil {
		return nil
	}
	return &ExternalAppView{
		ID:         a.ID,
		Name:       a.Name,
		BaseURL:    a.BaseURL,
		ClientID:   a.ClientID,
		SSOType:    a.SSOType,
		FrameMode:  a.FrameMode,
		Scopes:     a.Scopes,
		Placement:  a.Placement,
		IconURL:    a.IconURL,
		SortOrder:  a.SortOrder,
		Visibility: a.Visibility,
		Status:     a.Status,
		CreatedBy:  a.CreatedBy,
		CreatedAt:  a.CreatedAt,
		UpdatedAt:  a.UpdatedAt,
	}
}
