package store

import (
	"net/url"
	"sort"
	"strings"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
	"go.uber.org/zap"
	"trustmesh/backend/internal/model"
	"trustmesh/backend/internal/transport"
)

// CreateExternalAppInput is the payload for registering a new external platform.
type CreateExternalAppInput struct {
	Name       string `json:"name"`
	BaseURL    string `json:"base_url"`
	ClientID   string `json:"client_id"`
	SSOType    string `json:"sso_type"`
	FrameMode  string `json:"frame_mode"`
	Scopes     string `json:"scopes"`
	Placement  string `json:"placement"`
	IconURL    string `json:"icon_url"`
	SortOrder  int    `json:"sort_order"`
	Visibility string `json:"visibility"`
}

// UpdateExternalAppInput is the payload for updating an external platform.
type UpdateExternalAppInput struct {
	Name       *string `json:"name,omitempty"`
	BaseURL    *string `json:"base_url,omitempty"`
	SSOType    *string `json:"sso_type,omitempty"`
	FrameMode  *string `json:"frame_mode,omitempty"`
	Scopes     *string `json:"scopes,omitempty"`
	Status     *string `json:"status,omitempty"`
	Placement  *string `json:"placement,omitempty"`
	IconURL    *string `json:"icon_url,omitempty"`
	SortOrder  *int    `json:"sort_order,omitempty"`
	Visibility *string `json:"visibility,omitempty"`
}

// validateBaseURL rejects anything that is not an absolute http(s) URL. Without
// this a malicious registration could make TrustMesh mint SSO tokens for
// javascript:, data: or file: targets.
func validateBaseURL(raw string) *transport.AppError {
	u, err := url.Parse(strings.TrimSpace(raw))
	if err != nil || u.Host == "" {
		return transport.Validation("invalid base_url", map[string]any{"base_url": "must be an absolute http(s) URL"})
	}
	switch strings.ToLower(u.Scheme) {
	case "http", "https":
		return nil
	default:
		return transport.Validation("invalid base_url", map[string]any{"base_url": "scheme must be http or https"})
	}
}

// validateFrameMode restricts the launch strategy to the supported set.
func validateFrameMode(v string) *transport.AppError {
	switch v {
	case model.ExternalFrameNewTab, model.ExternalFrameIframe:
		return nil
	default:
		return transport.Validation("invalid frame_mode", map[string]any{"frame_mode": "must be newtab|iframe"})
	}
}

// validatePlacement accepts a comma-separated set of known mount points
// (empty means the app is not mounted anywhere).
func validatePlacement(v string) *transport.AppError {
	for _, p := range strings.Split(v, ",") {
		switch strings.TrimSpace(p) {
		case "", model.ExternalPlacementSidebar, model.ExternalPlacementProjectTab:
			continue
		default:
			return transport.Validation("invalid placement", map[string]any{
				"placement": "must be a comma-separated set of sidebar|project_tab",
			})
		}
	}
	return nil
}

// validateVisibility restricts visibility to the supported set.
func validateVisibility(v string) *transport.AppError {
	switch v {
	case model.ExternalVisibilityPrivate, model.ExternalVisibilityPublic:
		return nil
	default:
		return transport.Validation("invalid visibility", map[string]any{"visibility": "must be private|public"})
	}
}

// CreateExternalApp registers a new external platform. The client_secret is
// generated by TrustMesh and returned exactly once in the view-less response
// (callers fetch it via the returned raw secret). Only the creator may manage
// the app afterwards.
func (s *Store) CreateExternalApp(userID string, in CreateExternalAppInput) (*model.ExternalAppView, string, *transport.AppError) {
	name := strings.TrimSpace(in.Name)
	baseURL := strings.TrimSpace(in.BaseURL)
	clientID := strings.TrimSpace(in.ClientID)
	if name == "" || baseURL == "" || clientID == "" {
		return nil, "", transport.Validation("invalid external app payload", map[string]any{
			"name":      "required",
			"base_url":  "required",
			"client_id": "required",
		})
	}
	if appErr := validateBaseURL(baseURL); appErr != nil {
		return nil, "", appErr
	}
	ssoType := strings.TrimSpace(in.SSOType)
	if ssoType == "" {
		ssoType = model.ExternalSSOTrustmeshJWT
	}
	frameMode := strings.TrimSpace(in.FrameMode)
	if frameMode == "" {
		frameMode = model.ExternalFrameNewTab
	}
	if appErr := validateFrameMode(frameMode); appErr != nil {
		return nil, "", appErr
	}
	placement := strings.TrimSpace(in.Placement)
	if appErr := validatePlacement(placement); appErr != nil {
		return nil, "", appErr
	}
	// Default to private: a newly registered app must never silently become
	// visible (and launchable) for every user on the platform.
	visibility := strings.TrimSpace(in.Visibility)
	if visibility == "" {
		visibility = model.ExternalVisibilityPrivate
	}
	if appErr := validateVisibility(visibility); appErr != nil {
		return nil, "", appErr
	}

	now := time.Now().UTC()
	app := &model.ExternalApp{
		ID:           newID(),
		Name:         name,
		BaseURL:      baseURL,
		ClientID:     clientID,
		ClientSecret: newID(), // 24-char random hex used as the shared HS256 secret
		SSOType:      ssoType,
		FrameMode:    frameMode,
		Scopes:       strings.TrimSpace(in.Scopes),
		Placement:    placement,
		IconURL:      strings.TrimSpace(in.IconURL),
		SortOrder:    in.SortOrder,
		Visibility:   visibility,
		Status:       model.ExternalAppStatusEnabled,
		CreatedBy:    userID,
		CreatedAt:    now,
		UpdatedAt:    now,
	}

	s.mu.Lock()
	s.externalApps[app.ID] = app
	if err := s.persistExternalAppUnsafe(app); err != nil {
		delete(s.externalApps, app.ID)
		s.mu.Unlock()
		return nil, "", mongoWriteError(err)
	}
	s.mu.Unlock()

	return app.ToView(), app.ClientSecret, nil
}

// canAccessExternalApp reports whether userID may see (and launch) the app.
// Public apps are visible to everyone; private apps only to their creator.
func canAccessExternalApp(a *model.ExternalApp, userID string) bool {
	if a == nil {
		return false
	}
	if a.Visibility == model.ExternalVisibilityPublic {
		return true
	}
	return a.CreatedBy != "" && a.CreatedBy == userID
}

// ListExternalApps returns the external platforms visible to userID (safe
// view): every public app plus the ones the user created. Private apps owned
// by other users are invisible — mounting apps in the sidebar made the
// previous "everyone sees everything" behaviour a token-issuance risk.
func (s *Store) ListExternalApps(userID string) []model.ExternalAppView {
	s.mu.RLock()
	defer s.mu.RUnlock()
	items := make([]model.ExternalAppView, 0, len(s.externalApps))
	for _, a := range s.externalApps {
		if !canAccessExternalApp(a, userID) {
			continue
		}
		items = append(items, *a.ToView())
	}
	sortExternalAppViews(items)
	return items
}

// sortExternalAppViews orders mounted apps by sort_order then name so the
// sidebar and project tabs render in a stable, predictable sequence.
func sortExternalAppViews(items []model.ExternalAppView) {
	sort.Slice(items, func(i, j int) bool {
		if items[i].SortOrder != items[j].SortOrder {
			return items[i].SortOrder < items[j].SortOrder
		}
		return items[i].Name < items[j].Name
	})
}

// GetExternalApp returns a single external platform (safe view), enforcing
// the same visibility rule as List.
func (s *Store) GetExternalApp(userID, id string) (*model.ExternalAppView, *transport.AppError) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	a, ok := s.externalApps[id]
	if !ok || !canAccessExternalApp(a, userID) {
		return nil, transport.NotFound("external app not found")
	}
	return a.ToView(), nil
}

// GetExternalAppForLaunch resolves an app for the launch flow, enforcing
// visibility. Returns NotFound (not Forbidden) for invisible apps so the
// existence of a private registration is never disclosed.
func (s *Store) GetExternalAppForLaunch(userID, id string) (*model.ExternalApp, *transport.AppError) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	a, ok := s.externalApps[id]
	if !ok || !canAccessExternalApp(a, userID) {
		return nil, transport.NotFound("external app not found")
	}
	return a, nil
}

// GetExternalAppRaw returns the full record including the client_secret.
// Used internally by the launch flow (never serialized to API clients).
func (s *Store) GetExternalAppRaw(id string) (*model.ExternalApp, *transport.AppError) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	a, ok := s.externalApps[id]
	if !ok {
		return nil, transport.NotFound("external app not found")
	}
	return a, nil
}

// UpdateExternalApp updates an existing external platform. Only the creator
// may update it.
func (s *Store) UpdateExternalApp(userID, id string, in UpdateExternalAppInput) (*model.ExternalAppView, *transport.AppError) {
	s.mu.Lock()
	defer s.mu.Unlock()
	a, ok := s.externalApps[id]
	if !ok {
		return nil, transport.NotFound("external app not found")
	}
	if a.CreatedBy != userID {
		return nil, transport.Forbidden("not allowed to manage this external app")
	}
	if in.Name != nil {
		if n := strings.TrimSpace(*in.Name); n == "" {
			return nil, transport.Validation("invalid name", map[string]any{"name": "cannot be empty"})
		} else {
			a.Name = n
		}
	}
	if in.BaseURL != nil {
		if u := strings.TrimSpace(*in.BaseURL); u == "" {
			return nil, transport.Validation("invalid base_url", map[string]any{"base_url": "cannot be empty"})
		} else if appErr := validateBaseURL(u); appErr != nil {
			return nil, appErr
		} else {
			a.BaseURL = u
		}
	}
	if in.SSOType != nil && strings.TrimSpace(*in.SSOType) != "" {
		a.SSOType = strings.TrimSpace(*in.SSOType)
	}
	if in.FrameMode != nil && strings.TrimSpace(*in.FrameMode) != "" {
		fm := strings.TrimSpace(*in.FrameMode)
		if appErr := validateFrameMode(fm); appErr != nil {
			return nil, appErr
		}
		a.FrameMode = fm
	}
	if in.Scopes != nil {
		a.Scopes = strings.TrimSpace(*in.Scopes)
	}
	if in.Placement != nil {
		p := strings.TrimSpace(*in.Placement)
		if appErr := validatePlacement(p); appErr != nil {
			return nil, appErr
		}
		a.Placement = p
	}
	if in.IconURL != nil {
		a.IconURL = strings.TrimSpace(*in.IconURL)
	}
	if in.SortOrder != nil {
		a.SortOrder = *in.SortOrder
	}
	if in.Visibility != nil {
		v := strings.TrimSpace(*in.Visibility)
		if appErr := validateVisibility(v); appErr != nil {
			return nil, appErr
		}
		a.Visibility = v
	}
	if in.Status != nil {
		st := strings.TrimSpace(*in.Status)
		if st != model.ExternalAppStatusEnabled && st != model.ExternalAppStatusDisabled {
			return nil, transport.Validation("invalid status", map[string]any{"status": "must be enabled|disabled"})
		}
		a.Status = st
	}
	a.UpdatedAt = time.Now().UTC()
	if err := s.persistExternalAppUnsafe(a); err != nil {
		return nil, mongoWriteError(err)
	}
	return a.ToView(), nil
}

// DeleteExternalApp disconnects (removes) an external platform. Only the
// creator may delete it. Revocation is immediate: no new tokens can be issued.
func (s *Store) DeleteExternalApp(userID, id string) *transport.AppError {
	s.mu.Lock()
	defer s.mu.Unlock()
	a, ok := s.externalApps[id]
	if !ok {
		return transport.NotFound("external app not found")
	}
	if a.CreatedBy != userID {
		return transport.Forbidden("not allowed to manage this external app")
	}
	delete(s.externalApps, id)
	if s.mongoEnabled && s.mongoExternalApps != nil {
		ctx, cancel := s.mongoContext()
		defer cancel()
		if _, err := s.mongoExternalApps.DeleteOne(ctx, bson.M{"_id": id}); err != nil {
			return mongoWriteError(err)
		}
	}
	return nil
}

// RecordExternalAppLaunch writes an audit event for a launch action.
func (s *Store) RecordExternalAppLaunch(userID, appID, appName, projectID, taskID string) {
	if !s.mongoEnabled || s.mongoEvents == nil {
		return
	}
	ctx, cancel := s.mongoContext()
	defer cancel()
	content := "launched external app: " + appName
	event := model.Event{
		ID:        newID(),
		UserID:    userID,
		ProjectID: projectID,
		TaskID:    taskID,
		ActorType: "user",
		ActorID:   userID,
		EventType: "external_app_launch",
		Content:   &content,
		Metadata: map[string]any{
			"app_id":     appID,
			"app_name":   appName,
			"project_id": projectID,
			"task_id":    taskID,
		},
		CreatedAt: time.Now().UTC(),
	}
	if _, err := s.mongoEvents.InsertOne(ctx, event); err != nil && s.log != nil {
		s.log.Warn("failed to record external app launch audit event", zap.Error(err))
	}
}

// loadExternalApps loads all external apps from mongo into the in-memory map.
func (s *Store) loadExternalApps() (map[string]*model.ExternalApp, error) {
	out := make(map[string]*model.ExternalApp)
	if !s.mongoEnabled || s.mongoExternalApps == nil {
		return out, nil
	}
	ctx, cancel := s.mongoContext()
	defer cancel()
	cur, err := s.mongoExternalApps.Find(ctx, bson.M{})
	if err != nil {
		return out, err
	}
	defer cur.Close(ctx)
	for cur.Next(ctx) {
		var app model.ExternalApp
		if err := cur.Decode(&app); err != nil {
			return out, err
		}
		// Records written before mount metadata existed have an empty
		// visibility; default them to private so they never become visible to
		// everyone just because a new field was introduced.
		if app.Visibility == "" {
			app.Visibility = model.ExternalVisibilityPrivate
		}
		out[app.ID] = &app
	}
	return out, cur.Err()
}

// persistExternalAppUnsafe upserts an external app. Caller must hold s.mu.
func (s *Store) persistExternalAppUnsafe(app *model.ExternalApp) error {
	if !s.mongoEnabled || s.mongoExternalApps == nil || app == nil {
		return nil
	}
	ctx, cancel := s.mongoContext()
	defer cancel()
	_, err := s.mongoExternalApps.ReplaceOne(ctx, bson.M{"_id": app.ID}, app, options.Replace().SetUpsert(true))
	return err
}
